map_type: costmap
transform_tolerance: 0.5
obstacle_range: 2.5
raytrace_range: 4.0
resolution: 0.05
inscribed_radius: 0.35
circumscribed_radius: 0.4
inflation_radius: 0.3
cost_scaling_factor: 10.0
lethal_cost_threshold: 100
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25],[0.25, -0.25]]
observation_sources: base_scan
base_scan: {data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}
