local_costmap:
  update_frequency: 6
  publish_frequency: 6
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  publish_voxel_map : true
  unknown_cost_value : 255
  track_unkown_space : true
